// Embeds the AI prompt bodies (src/prompts/*.md) into a committed TypeScript
// module (src/prompts/generated.ts) so they ship inside the compiled bundle —
// no runtime filesystem access, and the published Docker image (which only
// copies `dist`) always has them. See docs/adr/0002-ai-prompt-architecture.md §2.
//
// This is intentionally NOT chained to `npm run build`: the Dockerfile does not
// copy `scripts/`, so a `prebuild` hook would ENOENT in the image. Run it
// manually via `npm run gen:prompts` after editing a prompt; the drift test
// (src/prompts/generated.test.ts) fails CI if the committed file is stale.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const promptsDir = join(here, "..", "src", "prompts");

export function buildGeneratedSource() {
  const ids = readdirSync(promptsDir)
    .filter((name) => name.endsWith(".md"))
    .map((name) => name.replace(/\.md$/, ""))
    .sort();

  const entries = ids
    .map((id) => {
      const body = readFileSync(join(promptsDir, `${id}.md`), "utf8");
      return `  ${JSON.stringify(id)}: ${JSON.stringify(body)},`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/gen-prompts.mjs from src/prompts/*.md.
// Do not edit by hand. Run \`npm run gen:prompts\` to regenerate.
export const PROMPTS: Record<string, string> = {
${entries}
};
`;
}

const outPath = join(promptsDir, "generated.ts");

// When imported by the drift test, only export the builder; when run directly,
// write the file.
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  writeFileSync(outPath, buildGeneratedSource());
  console.log(`wrote ${outPath}`);
}
